# ---------------------------------------------------------------------------- #
#                    GENERAL PARTICLE SOURCE DEFAULT CONFIOG                   #
# ---------------------------------------------------------------------------- #

/particleEnergyRandom/DebbuggingModeIsOn false


/gps/verbose 0
/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0 0 -2.3 cm
/gps/pos/halfx 4.0 cm
/gps/pos/halfy 4.0 cm
/gps/direction 0 0 1
/gps/ene/type Lin
/gps/ene/min 0.01 MeV
/gps/ene/max 100 MeV
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ang/maxtheta 0 deg
/gps/ang/mintheta 0 deg




# ---------------------------------------------------------------------------- #
#                       DEFAULT FILE NAME FOR SAVING DATA                      #
# ---------------------------------------------------------------------------- #
/NameOfFile/NameOfFile gamma_run
/run/beamOn 1000000



