# ---------------------------------------------------------------------------- #
#                                SIMULATION RUN                                #
# ---------------------------------------------------------------------------- #
#
# - No debugging mode (random)
# - Isotropic flux generation from a surface
# - Electrons protons alpha muons
#
# - energy spectrum flat
#
#

/particleEnergyRandom/DebbuggingModeIsOn false

/gps/verbose 0
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0 0 -2.4 cm
/gps/pos/halfx 6.0 cm
/gps/pos/halfy 6.0 cm
/gps/ang/type iso
/gps/ene/type Pow
/gps/ene/alpha 1.0


/gps/ang/maxtheta 90 deg
/gps/ang/mintheta 0 deg

 # ---------------------------------------------------------------------------- #
 #                                   ELECTRONS                                  #
 # ---------------------------------------------------------------------------- #

/gps/particle e-
/gps/ene/min 0.08 MeV
/gps/ene/max 12 MeV

/NameOfFile/NameOfFile 27_12_2022_ELECTRON
/run/beamOn 50000000

 # ---------------------------------------------------------------------------- #
 #                                    PROTONS                                   #
 # ---------------------------------------------------------------------------- #

/gps/particle proton
/gps/ene/min 0.01 MeV
/gps/ene/max 100 MeV

/NameOfFile/NameOfFile 27_12_2022_PROTON
/run/beamOn 50000000

 # ---------------------------------------------------------------------------- #
 #                                     ALPHA                                    #
 # ---------------------------------------------------------------------------- #

/gps/particle alpha
/gps/ene/min 2 MeV
/gps/ene/max 400 MeV

/NameOfFile/NameOfFile 27_12_2022_ALPHA
/run/beamOn 50000000

