# Run Si 27 12 2022 #


/particleEnergyRandom/DebbuggingModeIsOn true
/particleEnergyRandom/IsExponential true




# --------------------------------- ELECTRON --------------------------------- #

/gun/particle e-
/particleEnergyRandom/Ek_min 0.094
/particleEnergyRandom/Ek_max 10.0
/NameOfFile/NameOfFile ELECTRON_Si_28122022
#/run/beamOn 5000000


# ----------------------------------- PROTON --------------------------------- #

/gun/particle proton
/particleEnergyRandom/Ek_min 3.
/particleEnergyRandom/Ek_max 100.0
/NameOfFile/NameOfFile PROTON_Si_28122022
#/run/beamOn 5000000


# ----------------------------------- ALPHA ---------------------------------- #

/gun/particle alpha
/particleEnergyRandom/Ek_min 10.
/particleEnergyRandom/Ek_max 320.0
/NameOfFile/NameOfFile ALPHA_Si_28122022
#/run/beamOn 5000000


# ----------------------------------- GAMMA ---------------------------------- #

/gun/particle gamma
/particleEnergyRandom/Ek_min 0.05
/particleEnergyRandom/Ek_max 2.
/NameOfFile/NameOfFile GAMMA_Si_28122022
/run/beamOn 5000000