# ---------------------------------------------------------------------------- #
#                    GENERAL PARTICLE SOURCE DEFAULT CONFIOG                   #
# ---------------------------------------------------------------------------- #
/gps/verbose 0
/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0 0 -2.3 cm
/gps/pos/halfx 5.0 cm
/gps/pos/halfy 5.0 cm
/gps/ang/type iso
/gps/ene/type Pow
/gps/ene/alpha -1
/gps/ene/min 0.01 MeV
/gps/ene/max 200 MeV
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ang/maxtheta 0 deg
/gps/ang/mintheta 0 deg


# ---------------------------------------------------------------------------- #
#                    PARTICLE GUN FOR DEBUGGING MODE CONFIOG                   #
# ---------------------------------------------------------------------------- #

/particleEnergyRandom/DebbuggingModeIsOn false


#/process/em/auger true
#/process/em/augerCascade true
#/process/em/pixe true
#/process/em/fluo true
#/process/em/fluoANSTO true
#/process/em/fluoBearden true

#/cuts/setLowEdge 10 eV
#/cuts/setHighEdge 2 TeV



# SETTAGGIO DEI CUTS (EVENTUALMENTE ANCHE PER SINGOLA PARTICELLA - VEDI COMANDI COMMENTATI)
#/run/setCut 10 nm

/process/msc/StepLimit UseSafetyPlus







# ---------------------------------------------------------------------------- #
#                       DEFAULT FILE NAME FOR SAVING DATA                      #
# ---------------------------------------------------------------------------- #
/NameOfFile/NameOfFile gamma.root

/run/initialize
/run/beamOn 1000000




