/control/verbose 2
/control/saveHistory
/run/verbose 2

/vis/open OGL 600x600-0+0
/vis/viewer/zoom 1.2
/vis/drawVolume
/vis/viewer/set/autoRefresh false


/vis/viewer/set/auxiliaryEdge false
/vis/viewer/set/lineSegmentsPerCircle 100


/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set neutron magenta
/vis/modeling/trajectories/drawByParticleID-0/set pi+ black
/vis/modeling/trajectories/drawByParticleID-0/set pi- black
/vis/modeling/trajectories/drawByParticleID-0/set pi0 black


/vis/set/textColour 0. 0. 0.
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 20 ! ! SPARKLE

/vis/viewer/set/globalLineWidthScale 2.5

/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)

/vis/viewer/set/background white

/vis/geometry/set/lineWidth all 3

/vis/viewer/set/projection p

/vis/viewer/set/upVector 0 0 -1

/vis/viewer/set/rotationStyle constrainUpDirection
/vis/viewer/set/viewpointThetaPhi 160 225 deg
/vis/viewer/set/lightsThetaPhi 160 225 deg

#/vis/viewer/set/viewpointVector 0 1 0
#/vis/viewer/set/lightsVector 0 1 0


#/vis/scene/add/scale 10 cm x 0. 0. 0. manual 0. -7. 0. cm
#/vis/scene/add/scale 10 cm y 0. 0. 0. manual -7. 0. 0. cm

#/vis/viewer/set/globalLineWidthScale 2.5
#/vis/viewer/set/globalMarkerScale 2.5

# Frame
/vis/set/colour red
/vis/set/lineWidth 3
#/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
#/vis/set/lineWidth     # Revert to default line width (1.)


#######################################
#           Visibility
#######################################
/vis/geometry/set/visibility logicWorld 0 false
/vis/geometry/set/visibility logicContainer 0 false

#######################################
#           Colours
#######################################
/vis/viewer/set/style surface

#/vis/scene/add/logo 2.4 cm -z 1 0 0 manual  0 -8.3 0 cm
/vis/scene/add/logo2D 30 -0.9 -0.9 left

/vis/geometry/set/colour logicScintVeto    0 1. 1. 0.    1
/vis/geometry/set/colour logicDrilledVeto  0 0.3 0.3 1. 0.5
/vis/geometry/set/colour logicDrilledAl    0 0.6 0.6 0.6  0.2
/vis/geometry/set/colour logicPCBThin      0 1. 0.4 0.2 1.
/vis/geometry/set/colour logicLateralVeto  0 0.3 0.8 8    1.

#/vis/viewer/addCutawayPlane 0 0 0 m 1 0 0

/vis/viewer/set/hiddenMarker false



/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 10
/vis/ogl/set/displayListLimit 10000000
/vis/viewer/set/autoRefresh true

/vis/viewer/set/globalMarkerScale 1
/vis/viewer/set/globalLineWidthScale 1



#/vis/viewer/addCutawayPlane 0 2.5 0 cm 0 -1 0
/vis/viewer/set/projection p
/vis/viewer/set/viewpointVector 0 1 0
